// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjoKj3QePGrFV5ptxRx7DmXtBK-oWc_Ik',
    appId: '1:672486874106:web:f9f4dc3cde57e327b22243',
    messagingSenderId: '672486874106',
    projectId: 'sabie-c6b10',
    authDomain: 'sabie-c6b10.firebaseapp.com',
    storageBucket: 'sabie-c6b10.firebasestorage.app',
    measurementId: 'G-38BY5EMS8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXmoRMxZWncOCVqwZAu2Ql0RYkKCuEnI',
    appId: '1:672486874106:android:f1138a07fa685b2cb22243',
    messagingSenderId: '672486874106',
    projectId: 'sabie-c6b10',
    storageBucket: 'sabie-c6b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpeNnoo7ckHGht2Zub4qEy1ARfRLEHHk',
    appId: '1:672486874106:ios:13146e0771d7c4c5b22243',
    messagingSenderId: '672486874106',
    projectId: 'sabie-c6b10',
    storageBucket: 'sabie-c6b10.firebasestorage.app',
    iosBundleId: 'com.example.sabie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpeNnoo7ckHGht2Zub4qEy1ARfRLEHHk',
    appId: '1:672486874106:ios:13146e0771d7c4c5b22243',
    messagingSenderId: '672486874106',
    projectId: 'sabie-c6b10',
    storageBucket: 'sabie-c6b10.firebasestorage.app',
    iosBundleId: 'com.example.sabie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjoKj3QePGrFV5ptxRx7DmXtBK-oWc_Ik',
    appId: '1:672486874106:web:ae3e3d32c01f5542b22243',
    messagingSenderId: '672486874106',
    projectId: 'sabie-c6b10',
    authDomain: 'sabie-c6b10.firebaseapp.com',
    storageBucket: 'sabie-c6b10.firebasestorage.app',
    measurementId: 'G-VKKQNTQERX',
  );
}
